=== SriwanKm/pokedex/pokedex.dtd
<!--Jenna's DVD library-->
        <!--author: Sriwan Khaomuang-->
        <!--date: 12/17/20-->
        <!--filename: pokedex.dtd-->

        <!ELEMENT pokedex (pokemon+)>
        <!ELEMENT pokemon (types, species, gen, abilities, baseExp, growthRate, img)>
        <!ATTLIST pokemon name CDATA #REQUIRED>

        <!ELEMENT types (type+)>
        <!ELEMENT abilities (ability+)>
        <!ATTLIST abilities hidden CDATA #IMPLIED>

        <!ELEMENT type (#PCDATA)>
        <!ELEMENT species (#PCDATA)>
        <!ELEMENT gen (#PCDATA)>
        <!ELEMENT ability (#PCDATA)>
        <!ELEMENT baseExp (#PCDATA)>
        <!ELEMENT growthRate (#PCDATA)>
        <!ELEMENT img (#PCDATA)>

=== SriwanKm/pokedex/pokemon.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!--   Pokemon catalogue-->
<!--   Author: Sriwan Khaomuang-->
<!--   Date:   12/14/2020-->
<!--   Filename: pokemon.xml-->

<!DOCTYPE pokedex SYSTEM "pokedex.dtd">
<?xml-stylesheet type="text/xsl" href="pokemon.xsl" ?>

<pokedex>

    <pokemon name="Electabuzz">
        <types>
            <type>ELECTRIC</type>
        </types>
        <species>Electric Pokémon</species>
        <gen>1</gen>
        <abilities hidden="Vital Spirit">
            <ability>Static</ability>
        </abilities>
        <baseExp>172</baseExp>
        <growthRate>Medium Fast</growthRate>
        <img>electabuzz.jpg</img>

    </pokemon>

    <pokemon name="Pikachu">
        <types>
            <type>ELECTRIC</type>
        </types>
        <species>Mouse Pokémon</species>
        <gen>1</gen>
        <abilities hidden="Lightning Rod">
            <ability>Static</ability>
        </abilities>
        <baseExp>112</baseExp>
        <growthRate>Medium Fast</growthRate>
        <img>pikachu.jpg</img>

    </pokemon>


    <pokemon name="Raikou">
        <types>
            <type>ELECTRIC</type>
        </types>
        <species>Thunder</species>
        <gen>2</gen>
        <abilities hidden="Inner Focus">
            <ability>Pressure</ability>
        </abilities>
        <baseExp>261</baseExp>
        <growthRate>Slow</growthRate>
        <img>raikou.jpg</img>

    </pokemon>


    <pokemon name="Pincurchin">
        <types>
            <type>ELECTRIC</type>
        </types>
        <species>Sea Urchin</species>
        <gen>8</gen>
        <abilities hidden="Electric Surge">
            <ability>Lightning Rod</ability>
        </abilities>
        <baseExp>-</baseExp>
        <growthRate>Medium Fast</growthRate>
        <img>pincurchin.jpg</img>

    </pokemon>


    <pokemon name="Galvantula">
        <types>
            <type>ELECTRIC</type>
            <type>BUG</type>
        </types>
        <species>EleSpider</species>
        <gen>5</gen>
        <abilities hidden="Swarm">
            <ability>Compound Eyes</ability>
            <ability>Unnerve</ability>
        </abilities>
        <baseExp>165</baseExp>
        <growthRate>Medium Fast</growthRate>
        <img>galvantula.jpg</img>


    </pokemon>


    <pokemon name="Zeraora">
        <types>
            <type>ELECTRIC</type>
            <type>BUG</type>
        </types>
        <species>Thunderclap Pokémon</species>
        <gen>8</gen>
        <abilities>
            <ability>Volt Absorb</ability>
        </abilities>
        <baseExp>270</baseExp>
        <growthRate>Slow</growthRate>
        <img>zeraora.jpg</img>


    </pokemon>


</pokedex>
